<a href="https://colab.research.google.com/github/Danilzs/Analise-Sus/blob/main/An%C3%A1lise_Sus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import html

base = pd.read_csv(
    '/Base.csv',
    skiprows=1
)

# Corrigindo nomes das colunas
base.columns = [html.unescape(c) for c in base.columns]

# Corrigindo textos das células
base = base.apply(
    lambda col: col.map(
        lambda x: html.unescape(x)
        if isinstance(x, str)
        else x
    )
)

base.head()

,Município [-],Código [-],Gentílico [-],Prefeito [2025],Área Territorial - km² [2025],População no último censo - pessoas [2022],Densidade demográfica - hab/km² [2022],População estimada - pessoas [2025],Escolarização <span>6 a 14 anos</span> - % [2022],IDHM <span>Índice de desenvolvimento humano municipal</span> [2010],Mortalidade infantil - óbitos por mil nascidos vivos [2023],Total de receitas brutas realizadas - R$ [2024],Total de despesas brutas empenhadas - R$ [2024],PIB per capita - R$ [2023],Unnamed: 14
0,Abaiara,2300101,abaiarense,ANGELO FURTADO SAMPAIO,180.833,10038,55.51,10269,99.69,0.628,-,62478227.64,55577854.04,14318.54,NaN
1,Acarape,2300150,acarapense,FRANCISCO EDILBERTO BESERRA BARROSO,129.767,14027,107.90,14340,97.64,0.606,-,99314234.62,93260342.18,15717.86,NaN
2,Acaraú,2300200,acarauense,ANA FLÁVIA RIBEIRO MONTEIRO,842.469,65264,77.47,69317,99.45,0.601,7.79,355004235.11,342565319.59,19156.82,NaN
3,Acopiara,2300309,acopiarense,FRANCISCO VILMAR FELIX MARTINS,2254.279,44962,19.95,45937,99.45,0.595,4.42,232541466.38,226807403.04,15424.91,NaN
4,Aiuaba,2300408,aiuabense,JOSE MORAES FEITOSA,2438.563,14076,5.77,14115,98.87,0.569,8.2,89022174.43,85657480.56,12011.64,NaN

In [3]:
base = base[
[
'Município [-]',
'Código [-]',
'População no último censo - pessoas [2022]',
'IDHM <span>Índice de desenvolvimento humano municipal</span> [2010]',
'Densidade demográfica - hab/km² [2022]'
]
]

#peguei somente as colunas necessarias

In [4]:
base.columns = [
'MUNICIPIO',
'CODIGO',
'POPULACAO',
'IDH',
'DENSIDADE'
]

base['MUNICIPIO'] = (
    base['MUNICIPIO']
    .str.upper()
    .str.strip()
)

In [5]:
base.head()

  MUNICIPIO   CODIGO POPULACAO    IDH DENSIDADE
0   ABAIARA  2300101     10038  0.628     55.51
1   ACARAPE  2300150     14027  0.606    107.90
2    ACARAÚ  2300200     65264  0.601     77.47
3  ACOPIARA  2300309     44962  0.595     19.95
4    AIUABA  2300408     14076  0.569      5.77

In [6]:
base.to_csv(
    '/content/base_ibge_limpa.csv',
    index=False,
    encoding='utf-8'
)

In [7]:
import pandas as pd

sus = pd.read_csv('/content/sus.txt', sep=',')

sus.head()

   ID                                          MUNICÍPIO PRIMEIRO_NOME
0   1  ABAIARA                                       ...       ADRIANA
1   2  ABAIARA                                       ...       ADRIANA
2   3  ABAIARA                                       ...         ALINE
3   4  ABAIARA                                       ...       ALZENIR
4   5  ABAIARA                                       ...           ANA

In [8]:
sus['MUNICÍPIO'] = (
    sus['MUNICÍPIO']
    .str.upper()
    .str.strip()
)

sus.columns = [
    'ID',
    'MUNICIPIO',
    'PRIMEIRO_NOME'
]

sus.head()

   ID MUNICIPIO PRIMEIRO_NOME
0   1   ABAIARA       ADRIANA
1   2   ABAIARA       ADRIANA
2   3   ABAIARA         ALINE
3   4   ABAIARA       ALZENIR
4   5   ABAIARA           ANA

In [9]:
import unicodedata

def remover_acentos(txt):
    if isinstance(txt, str):
        return ''.join(
            c for c in unicodedata.normalize('NFKD', txt)
            if not unicodedata.combining(c)
        )
    return txt

sus['MUNICIPIO'] = (
    sus['MUNICIPIO']
    .str.upper()
    .str.strip()
    .apply(remover_acentos)
)

base['MUNICIPIO'] = (
    base['MUNICIPIO']
    .str.upper()
    .str.strip()
    .apply(remover_acentos)
)

In [16]:
sus['MUNICIPIO'] = sus['MUNICIPIO'].replace(
    {'ITAPAGE':'ITAPAJE'}
)
#Na base do ibge tava escrito Itapaje e na do Sus, Itapage, então corrigi.

In [17]:
final = sus.merge(
    base,
    on='MUNICIPIO',
    how='left'
)

final.head()

   ID MUNICIPIO PRIMEIRO_NOME   CODIGO POPULACAO    IDH DENSIDADE
0   1   ABAIARA       ADRIANA  2300101     10038  0.628     55.51
1   2   ABAIARA       ADRIANA  2300101     10038  0.628     55.51
2   3   ABAIARA         ALINE  2300101     10038  0.628     55.51
3   4   ABAIARA       ALZENIR  2300101     10038  0.628     55.51
4   5   ABAIARA           ANA  2300101     10038  0.628     55.51

In [18]:
final.isnull().sum()

ID               0
MUNICIPIO        0
PRIMEIRO_NOME    1
CODIGO           0
POPULACAO        0
IDH              0
DENSIDADE        0
dtype: int64